### ISSUE TITLE
GitHub pages deployment

### ISSUE THREAD

**Issue by vsoch** [con/tributors#16]
@yarikoptic the site doesn't seem to render to https://con.github.io/tributors/ and I believe this is because you have a CNAME in some repo on here. I'm worried that this doesn't have https, which (other than not being secure) looks really unprofessional. Could you please comment?

**Comment by vsoch** [comment]
Note, I'm hosting on my fork for the time being - has https and the whole bit. https://vsoch.github.io/tributors/

**Comment by yarikoptic** [comment]
https://con.github.io/tributors/ seems to render for me just fine. Not aware of any repo here with cname. May be just was a delay?

**Comment by yarikoptic** [comment]
Btw website says

© 2019 @vsoch All Rights Reserved

**Comment by vsoch** [comment]
Huh I'm still getting 404!

![image](https://user-images.githubusercontent.com/814322/86292722-7a5f7000-bbae-11ea-8433-a3a3621e014a.png)

**Comment by vsoch** [comment]
(Cache disabled)

**Comment by yarikoptic** [comment]
![Screenshot_20200701-172621](https://user-images.githubusercontent.com/39889/86293130-0b8b1280-bbc0-11ea-87b5-79e34b206fdc.png)

**Comment by yarikoptic** [comment]
I think it is some cdn oddity, give it some time. I will later test from laptop as well

**Comment by vsoch** [comment]
phew, it's showing up for me now too! Thank goodness!! Closing.

**Comment by vsoch** [comment]
I blame Microsoft. It must be their fault.
