### ISSUE TITLE
target use case: initiate .zenodo.json from information available

### ISSUE THREAD

**Issue by yarikoptic** [con/tributors#22]
I know that it is WiP, but just wanted to create a dedicated issue to know when I should try tributors e.g. on https://github.com/con/open-brain-consent which as `.all-contributorsrc`.  My blind attempt to "trick" tributors resulted in an error which I have no clue where it came from (what was not found) and what I should do (configuration?):

```shell
(git-annex)lena:~/proj/open-brain-consent[master]
$> tributors update
.zenodo.json does not exist

$> echo '{}' > .zenodo.json

$> tributors update zenodo 
INFO:zenodo:Updating .zenodo.json
Response 404: Not Found, cannot retrieve contributors.
```

**Comment by vsoch** [comment]
If you want to specifically update an `.allcontributorsrc` then you would need to specify that.
```bash
$ tributors update allcontrib
```
When you leave out the third word:
```bash
$ tributors update
```
You are basically defaulting to "all"

```bash
$ tributors update all
```

And note that this is documented here https://con.github.io/tributors/docs/getting-started#3-update-contributors-1.
But we could do this differently, perhaps search for existing files (known to tributors) and update based on that?

**Comment by vsoch** [comment]
okay I fixed this so that it better auto-detects, because you're right it's nice to just be able to run `tributors update` and have it update the files it knows about. PR coming soon!

**Comment by vsoch** [comment]
@yarikoptic I addressed this in the PR I just merged, so please test now in the way you tried earlier, just the update in a repository with an .all-contributorsrc should just update that. Also note that you will need to install tributors from GitHub, I haven't released since the original skeleton. E.g.,

```
git clone git@github.com:con/tributors
cd tributors
pip install -e .
```

**Comment by yarikoptic** [comment]
I didn't even know that it was released to pypi already ;) I tend to prefer local `pip install -e .` in a `git clone` for projects under development.
It does work now in that it adds contributor names!
```
$> echo '{}' > .zenodo.json
(dev3) 1 42585.....................................:Thu 02 Jul 2020 06:40:31 PM EDT:.
(git-annex)lena:~/proj/open-brain-consent[master]git
$> tributors update zenodo 
INFO:zenodo:Updating .zenodo.json
INFO:tributors:⭐️ new contributor yarikoptic
INFO:tributors:⭐️ new contributor vborghe
INFO:tributors:⭐️ new contributor allcontributors[bot]
INFO:tributors:⭐️ new contributor adswa
INFO:tributors:⭐️ new contributor CPernet
INFO:tributors:⭐️ new contributor jpellman
INFO:tributors:⭐️ new contributor mkoculak
INFO:tributors:⭐️ new contributor chrisgorgo
INFO:tributors:⭐️ new contributor mhavu
INFO:tributors:⭐️ new contributor sappelhoff
INFO:tributors:⭐️ new contributor AsykaKolbacyka
INFO:tributors:⭐️ new contributor hcp4715
INFO:tributors:⭐️ new contributor mlkieseler
INFO:tributors:⭐️ new contributor pjtoussaint
INFO:tributors:⭐️ new contributor PeerHerholz
INFO:tributors:⭐️ new contributor robertoostenveld
INFO:tributors:⭐️ new contributor satra
INFO:tributors:⭐️ new contributor jsheunis
INFO:tributors:⭐️ new contributor yarikoptic-private

$> head .zenodo.json
{
    "creators": [
        {
            "name": "Yaroslav Halchenko"
        },
        {
            "name": "vborghesani"
        },
        {
            "name": "Adina Wagner"
...
```
Now need to figure out how to make it talk to ORCID?  Should've it may be `tributors` issued some INFO message or WARNING that it is not going to talk to ORCID because xyz?

**Comment by vsoch** [comment]
You need to export first an ORCID_ID and ORCID_SECRET, and then just an ORCID_TOKEN that is generated for you from that. See details in the environment https://con.github.io/tributors/docs/getting-started#2-environment-1
