### ISSUE TITLE
Add support for update of lookup

### ISSUE THREAD

**Issue by yarikoptic** [con/tributors#28]
Follow up https://github.com/con/tributors/issues/22#issuecomment-653251074  where for vborghesani and pjtoussaint no name was added.  But there is a standard `git` feature to have `.mailmap` mapping different logins to desired ones. E.g. our simplistic one in OBC:
```
$> cat .mailmap 
Yaroslav O. Halchenko <debian@onerussian.com>
Yaroslav O. Halchenko <site-github-private@onerussian.com>
Valentina Borghesani <vborghe@users.noreply.github.com>
Marie-Luise Kieseler <kieseler.gr@dartmouth.edu>
Cyril Pernet <wamcyril@gmail.com>
Cyril Pernet <cyril.pernet@ed.ac.uk>
Stephan Heunis <jsheunis@gmail.com>
P.-J. Toussaint <4642250+pjtoussaint@users.noreply.github.com>
```
results in 
```
$> git shortlog -sn | nl
     1	   111	Yaroslav O. Halchenko
     2	    64	Cyril Pernet
     3	    35	Valentina Borghesani
     4	    34	allcontributors[bot]
     5	    21	Adina Wagner
     6	     6	John Pellman
     7	     5	Marcin Koculak
     8	     4	Chris Filo Gorgolewski
     9	     4	Marko Havu
    10	     2	Stefan Appelhoff
    11	     1	Anna Tovchigrechko
    12	     1	Chuan-Peng Hu
    13	     1	Marie-Luise Kieseler
    14	     1	P.-J. Toussaint
    15	     1	Peer Herholz
    16	     1	Robert Oostenveld
    17	     1	Satrajit Ghosh
    18	     1	Stephan Heunis
```

**Comment by vsoch** [comment]
Does anyone use that anymore? Can you show me some set of repos that have a mailmap file? I'm not convinced this would hit a lot of users...

**Comment by vsoch** [comment]
okay so I just went on my run, and I have a sense of what this issue is really about. The functionaliy that we haven't implemented yet is being able to say something like:

```
$ tributors update --from mailmap
$ tributors update allcontrib --from zenodo
```
So what we would want to do is add a `--from` parser that can handle some input source of emails, orcids, etc, and then the class would be able to parse the source to expose emails, other metadata, and then be able to update the initial file with them. For example it would do the following:

```
$ tributors update allcontrib --from zenodo
# 1. read in and parse all contrib file
# 2. read in zenodo
# 3. update initial all contrib entries with whatever is discovered via zenodo (likely just emails would be the mapping attribute)
# 4. then run a standard update for all contrib, the entries from zendo would be added.
```
I think this feature request would meet the initial use case of wanting "allcontrib2zenodo" but it was important to implemenet them modularly to start.

**Comment by vsoch** [comment]
Quick question though @yarikoptic - would we be saying "use this file as another lookup only for existing entires" OR "update the resource from this file" ? They are different. I think the `--from` I mentioned above would be for the latter, and if you really wanted to just use a file as a lookup, it would need a different interaction. Maybe like:

```
$ tributors update --use-lookup mailmap
```

**Comment by vsoch** [comment]
Anyway I'm done working for today! We will get these features added, not totally sure about the UI yet but it'll come to me :)

**Comment by vsoch** [comment]
Ahh I know! We would want to be able to update just the .tributors lookup / cache like

```bash
$ tributors update-lookup .mailmap
```
and then when .tributors is updated with names (would need to derive name based on matching email)

```bash
$ tributors update 
```
and this is still different from updating from another parser, that would be:

```bash
$ tributors update zenodo --from allcontrib
```
Yeah I think I like that :)

**Comment by yarikoptic** [comment]
> Does anyone use that anymore? Can you show me some set of repos that have a mailmap file? I'm not convinced this would hit a lot of users...

I used it for any project where I wanted to see who contributed how many commits... `git shortlog` is the goto command for that.  If `tributors` could help maintaining it -- would be good, but not really an immediate need. But it possibly could be used to harvest more info on contributors if that 

<details>
<summary>a quick list of .mailmaps I find on my drive under proj/</summary> 

```shell
$> ls -ld */.mailmap */*/.mailmap
-rw------- 1 yoh yoh  2151 May  8 10:27 bids/bids-validator/.mailmap
-rw------- 1 yoh yoh   411 Jan 15 12:31 bids/fitlins/.mailmap
-rw------- 1 yoh yoh  1331 Jan 10  2019 bids/grabbit/.mailmap
-rw------- 1 yoh yoh  1806 Feb 27  2019 bids/pybids-master/.mailmap
-rw------- 1 yoh yoh  1200 Jan 15 12:32 bids/pybids/.mailmap
-rw------- 1 yoh yoh   740 Jan 28 21:24 datalad/datalad-0.11.x/.mailmap
-rw------- 1 yoh yoh   740 Feb  6 20:19 datalad/datalad-0.12.x/.mailmap
-rw------- 1 yoh yoh   740 May 22 10:08 datalad/datalad-bug-try/.mailmap
-rw------- 1 yoh yoh   740 Feb 25 11:58 datalad/datalad-clone/.mailmap
-rw------- 1 yoh yoh   740 Mar  2 10:21 datalad/datalad-maint/.mailmap
-rw------- 1 yoh yoh   740 Dec 17  2018 datalad/datalad-master/.mailmap
-rw------- 1 yoh yoh   740 Oct  7  2019 datalad/datalad/.mailmap
-rw------- 1 yoh yoh   124 Jun 26  2018 duecredit-clone/.mailmap
-rw------- 1 yoh yoh   124 Jun 26  2018 duecredit/.mailmap
-rw------- 1 yoh yoh  2379 Aug 15  2017 git-annex/.mailmap
-rw------- 1 yoh yoh 10807 Jul 31  2018 ipykernel/.mailmap
-rw------- 1 yoh yoh 11477 Jul 31  2018 ipython/.mailmap
-rw------- 1 yoh yoh  7128 Jun 26  2018 matplotlib/.mailmap
-rw------- 1 yoh yoh   867 Dec  5  2012 misc/be/.mailmap
-rw------- 1 yoh yoh  4039 Jul 24  2013 misc/buildbot/.mailmap
-rw------- 1 yoh yoh  1689 Apr  5 21:22 misc/conda-constructor/.mailmap
-rw------- 1 yoh yoh 16159 May 11  2017 misc/docker/.mailmap
-rw------- 1 yoh yoh    43 Jun 20  2019 misc/fmriflows/.mailmap
-rw------- 1 yoh yoh 16981 May 29 22:17 misc/git/.mailmap
-rw------- 1 yoh yoh  1006 Oct 30  2019 misc/glances/.mailmap
-rw------- 1 yoh yoh  1663 May 18  2016 misc/h/.mailmap
-rw------- 1 yoh yoh  5895 Sep 23  2019 misc/h5py/.mailmap
-rw------- 1 yoh yoh  3529 Apr 20 13:02 misc/magit/.mailmap
-rw------- 1 yoh yoh 19000 Jun 20  2019 misc/scipy/.mailmap
-rw------- 1 yoh yoh   137 Mar 28  2018 misc/shablona/.mailmap
-rw------- 1 yoh yoh 18868 Feb 19  2018 misc/sympy/.mailmap
-rw------- 1 yoh yoh   208 Jun 29  2017 misc/tig/.mailmap
-rw------- 1 yoh yoh   763 Mar  2 10:41 misc/tqdm/.mailmap
-rw------- 1 yoh yoh    67 Aug 22  2014 neurosynth/neurosynth/.mailmap
-rw------- 1 yoh yoh   322 Apr 25  2012 numpy-vbench-copied/code/.mailmap
-rw------- 1 yoh yoh  1079 May  2  2013 numpy-vbench/numpy/.mailmap
-rw------- 1 yoh yoh  1079 Nov 19  2013 numpy-vbench/tmp_tmp/.mailmap
-rw------- 1 yoh yoh 18556 Feb  5 18:45 numpy/.mailmap
-rw------- 1 yoh yoh   380 May  9 17:58 open-brain-consent/.mailmap
-rw------- 1 yoh yoh   508 Oct 10  2019 pymvpa/pymvpa-master/.mailmap
-rw------- 1 yoh yoh   508 Oct 31  2017 pymvpa/pymvpa.clone/.mailmap
-rw------- 1 yoh yoh   508 Oct  4  2016 pymvpa/pymvpa/.mailmap
-rw------- 1 yoh yoh 27886 May  9 20:45 scipy/.mailmap
-rw------- 1 yoh yoh   131 Jun 23  2014 studyforrest/pelican-bootstrap3/.mailmap
```
</details>

**Comment by yarikoptic** [comment]
re `update` vs `update-lookup` - I am yet to grasp the difference...  So far I see that `.tributors` should become the ultimate "sink" of the information from other sources and also the "single point of manual entry/fixups" so other files could be updated/regenerated from it. `tributors update TO[ --from FROM FROM FROM]` sounds good.  My worry is about how to "react" if `FROM` changed some information while it was also updated in `.tributors` - how to detect and/or take advantage... although probably `TO` should always take precedence but then `.tributors` should also allow to "collect" sufficient information to detect previously analyzed (e.g. both `yarikoptic` and `yarikoptic-private` are me; multiple names might appear, etc)

**Comment by vsoch** [comment]
.tributors is a shared cache that is updated from GitHub contributors (and potentially other sources when we add update-lookup), but we don’t do direct updates from it (meaning, a user in .tributors not in a zenodo.json won’t just be added to the zenodo.json). The reason is because different parsers might have different users that shouldn’t just be crossed or merged. The update function is intended to update a contributor file. Update-lookup would just update the .tributors file, which then, when used as a lookup, would have new metadata. And finally, adding —from would be saying “Actually I do want to update people from zenodo to all contributors).

**Comment by vsoch** [comment]
This is done, and the addition of mailmap too. I'll open another issue for the next work, adding `--from`.

**Comment by vsoch** [comment]
@yarikoptic here is your example https://con.github.io/tributors/docs/parsers/mailmap. You'd update from mailmap before running a standard `update` to update contributor files.

**Comment by yarikoptic** [comment]
> The reason is because different parsers might have different users that shouldn’t just be crossed or merged

oh... I thought that is the sole purpose of .tributors -- to actually provide the "merged" information (possibly even through manual tune up), so then multiple files (`.all-contributorsrc`, `.zenodo.json` etc) could be updated using that possibly merged (and improved) information.

> Update-lookup would just update the .tributors file, which then, when used as a lookup, would have new metadata

`update` seems also to update it after updating the target file... I am still then not sure "what its purpose in life" besides indeed some boring cache (but then records aren't annotated for what service they are caching for).

**Comment by vsoch** [comment]
> oh... I thought that is the sole purpose of .tributors -- to actually provide the "merged" information (possibly even through manual tune up), so then multiple files (.all-contributorsrc, .zenodo.json etc) could be updated using that possibly merged (and improved) information.

It DOES that's the .tributors file!

**Comment by yarikoptic** [comment]
ah, ok ;-)  I guess I misunderstood initially the followup statement
