### ISSUE TITLE
Consider Orcid to retrieve metadata (requires hosted server)

### ISSUE THREAD

**Issue by vsoch** [con/tributors#3]
@yarikoptic I'm looking into adding Orcid now, but this is problematic because it's an Oauth2 flow, which requires to log in and then generate a client id and secret. E.g., if you go to https://orcid.org/developer-tools this is the only option - I don't see any option to just generate a one off token to use for GitHub actions, for example. How did you have in mind this would work? Requiring the user to generate an app and then login with it does not seem like it would work.

**Comment by yarikoptic** [comment]
I was looking into just having a tool, so it (locally) could have done oauth2 authentication given user's credentials and then do what it needs to do for that run, and possibly reauthenticate in the future. we do smth like that with github in datalad, but there I believe they are going to deprecate it in favor of using API tokens.
Also rclone provides an example for amazing handling of such interactions.

**Comment by vsoch** [comment]
Hmm I'll need to think about this because client id / tokens aren't typically for this kind of use case.

I made huge progress today, take a look at the https://github.com/con/tributors/tree/refactor/tributors branch if you are interested. I still need to update the Docker usage and action, and then think about if this is reasonable to add in some way, and how to add an interactive component. But I need to stop for today, have other stuffs to do.

**Comment by vsoch** [comment]
I hope you like the name too, it's perfect for this repo, my best lame name / pun yet!

> tributors: pay tribute to your contributors!

harharhrh

**Comment by vsoch** [comment]
And don't worry I'll open a PR when it's ready for review, going to add issues/todos at that time too.

**Comment by yarikoptic** [comment]
Ha ha ha - name is awesome!!

**Comment by yarikoptic** [comment]
You do have a talent for good names ;-)

**Comment by vsoch** [comment]
@yarikoptic I still am not clear how you expect this to work - an app that holds a key/token needs to have a hosted url, and a redirect url. This would require running a server, so I'm not sure what you have in mind for this to work?

**Comment by vsoch** [comment]
Actually let me fuss around with the Google playground as a redirect url, maybe it would work anyway! If they don't check that we have something running at localhost it might be possible. Testing now.

**Comment by vsoch** [comment]
okay I got the endpoints working, but the bad news is that it won't be useful for most:

![image](https://user-images.githubusercontent.com/814322/86176656-7ebe5700-bae2-11ea-848f-daf5335d76eb.png)

Just tested my email, returned no results!

**Comment by vsoch** [comment]
ha! I just got it working, I am able to use a first and last name fallback, and if there is more than one result I can show them to the user and say "pick one and add it."

**Comment by yarikoptic** [comment]
AWESOME!

**Comment by vsoch** [comment]
This is finished, we can open other issues if something comes up.
