### ISSUE TITLE
a collection based on OBC: collect emails to .tributors records, may be RF .tributors to allow for options, github for update-lookup

### ISSUE THREAD

**Issue by yarikoptic** [con/tributors#36]
I liked how .all-contributorsrc allows for consistent options storage alongside with the records, may be that should be done for .tributors?  Use case -- in majority (well, all open) projects emails of contributors are available in .mailmap, git commits and possibly as public record from github, zenodo, orcid etc.  They allow to "identify" contributors. But may be in some scenarios that would be undesired? then adding an option within .tributors telling to not store emails would help.

Without knowing emails I am not sure how `mailmap` extractor works, and it didn't do expected magic for me:
```
$> tributors update-lookup mailmap            
INFO:   mailmap:Updating .tributors cache from .mailmap

$> grep pjtouss .tributors .all-contributorsrc
.tributors:    "pjtoussaint": {
.tributors:        "name": "pjtoussaint"
.all-contributorsrc:      "login": "pjtoussaint",
.all-contributorsrc:      "name": "pjtoussaint",
.all-contributorsrc:      "profile": "https://github.com/pjtoussaint",

$> grep pjtouss .mailmap
P.-J. Toussaint <4642250+pjtoussaint@users.noreply.github.com>

$> git log | grep pjtouss
    Merge pull request #83 from con/all-contributors/add-pjtoussaint
    docs: add pjtoussaint as a contributor
    Added mailmap entries for jsheunis and pjtoussaint
    @pjtoussaint, Please check if introduced name is the preferable form for you.
Author: P.-J. Toussaint <4642250+pjtoussaint@users.noreply.github.com>
```
I expect that github would have provided the association (that the pjtoussaint contributed following commits, for which I could look up email address within repo).  BTW, I guess github should be added to `update-lookup`?
```
$> tributors update-lookup github 
usage: tributors update-lookup [-h] [{mailmap,allcontrib,codemeta,zenodo,unset} [{mailmap,allcontrib,codemeta,zenodo,unset} ...]]
tributors update-lookup: error: argument files: invalid choice: 'github' (choose from 'mailmap', 'allcontrib', 'codemeta', 'zenodo', 'unset')
```
since it seems the "sources" here, not necessarily destinations  .

**Comment by vsoch** [comment]
You can only update from a mailmap given that you have an email in your .tributors that can be mapped, and then at most it would update a name. That's how it works. GitHub isn't a lookup because it's basically how the core of the library works, but I could add it as a lookup option in case we just want to run that one bit.

**Comment by yarikoptic** [comment]
> I could add it as a lookup option in case we just want to run that one bit.

I think it is a valuable source for lookup since it binds github logins with emails, right?

**Comment by vsoch** [comment]
Yes definitely, but it's always run no matter what so I didn't think to add it. I'll add it with another PR.

**Comment by vsoch** [comment]
GitHub is added.
