### ISSUE TITLE
Create pretty docs on GitHub pages

### ISSUE THREAD

**Issue by vsoch** [con/tributors#4]

**Comment by vsoch** [comment]
Make sure to have:

 - problem statement
 - usage (command line / local, docker, github action)
 - quick start guide

**Comment by vsoch** [comment]
Maybe an idea for a logo? @yarikoptic ?

**Comment by vsoch** [comment]
I really like this emoji, 🙌️ so maybe a simplified version of that.

**Comment by yarikoptic** [comment]
good idea! I would not even care to simplify it, but would make sure it comes from some clipart with a permissive license; but then may be somehow reflect the "connectivity" aspect of this project -- that it assists with establishing files for all those zenodo etc? may be "multiple hands handshake" :
![image](https://user-images.githubusercontent.com/39889/86201139-b225d380-bb2c-11ea-9b1f-fc19f7afec2b.png)

**Comment by vsoch** [comment]
hey @yarikoptic do you know how to give me permission to create robot tokens? 
![image](https://user-images.githubusercontent.com/814322/86235920-7273e180-bb56-11ea-9291-4013c8c83b13.png)

If I can't have it, could you create a robot token with write permission, and add the DOCKER_USER and DOCKER_PASSWORD to the repository here to replace the current?

**Comment by vsoch** [comment]
Done https://vsoch.github.io/tributors/.
