### ISSUE TITLE
Update container to quay.io/con/tributors

### ISSUE THREAD

**Issue by vsoch** [con/tributors#6]
And this container should be used as the base for the action container, that way we have a much speedier run.

**Comment by vsoch** [comment]
@yarikoptic do you have a quay.io organization (or similar) to push to?

**Comment by yarikoptic** [comment]
I don't think I do yet. Should I establish one connected to this github org?

**Comment by vsoch** [comment]
You don't actually need to connect it, but just add my username to have permissions to manage it. I'll generate a robot with specific permissions to deploy.

**Comment by vsoch** [comment]
I'll create one under my account (vanessa) in the meantime to test, etc.

**Comment by vsoch** [comment]
Done https://quay.io/repository/vanessa/tributors?tab=tags.

**Comment by yarikoptic** [comment]
done - https://quay.io/repository/con/tributors you (vsoch) is added as admin.  I didn't link anything yet

**Comment by vsoch** [comment]
Great! I'll update for the next PR, and make the robot user, update the token, etc. Going to re-open this as a reminder.

**Comment by vsoch** [comment]
I can't do this until I have permission to make a robot user (I do not).

**Comment by yarikoptic** [comment]
who needs to give such permission? A new user on GitHub or where?

**Comment by vsoch** [comment]
I need to be able to generate a robot token. It's under settings for the repo - I copy pasted a screen shot in another issue.

**Comment by yarikoptic** [comment]
I found some screenshot while on the phone which showed that you are an admin but that there is no robot account.

https://stackoverflow.com/questions/29177623/what-is-a-bot-account-on-github suggests that bot account is just a regular account we would need to create and then add to this repo... or please walk me through on what I need to do.

**Comment by yarikoptic** [comment]
I will be on and off hanging out in https://meet.jit.si/DataLad if you like audio/video contact (unless my browser crashes again)

**Comment by vsoch** [comment]
I joined but you RAN AWAY

**Comment by vsoch** [comment]
@yarikoptic come back!
