### ISSUE TITLE
allcontributors bot and tributors workflow seem to have a different opinion on spaces

### ISSUE THREAD

**Issue by adswa** [con/tributors#70]
https://github.com/datalad/datalad-gooey uses both the GitHub tributors action - THANKS! - and the all-contributors bot (to easily credit non-commit contributions). https://github.com/datalad/datalad-gooey/pull/122/files seems to suggest that the bot and the action have a different taste about spaces. In practice, this causes the action to run after a [manual call to the bot](https://github.com/datalad/datalad-gooey/issues/52#issuecomment-1249298121). 

Edit: I just realized I'm not running the latest version (0.0.19) - whoops.

**Comment by vsoch** [comment]
It's that same client used under the hood, so the differences would likely result from the version installed https://github.com/con/tributors/blob/d8f3cdb3933826202231f24513d4fb62ab590135/Dockerfile#L17 or the generation command https://github.com/con/tributors/blob/d8f3cdb3933826202231f24513d4fb62ab590135/docker/entrypoint.sh#L105.

**Comment by adswa** [comment]
indeed, an update solved it :pray: thanks, sorry for the noise!

**Comment by vsoch** [comment]
No worries!
